version: '2'
services:

  frontend:
    build: ./courseify_client
    container_name: courseify_client
    command: npm run start
    ports:
      - '3001:80'
    volumes:
     - ./frontend:/courseify_client
    environment:
      NODE_ENV: development

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    container_name: couresify_db
    ports:
      - '5432'
      
  backend:
    build: ./courseify_api
    container_name: courseify_api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/backend
    environment:
      RAILS_ENV: development



volumes:
  db_data:
  bundle: