version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  backend:
    build: ./courseify_api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: ./courseify_client
    command: npm run start-build
    volumes:
      - .:/frontend
    ports:
      - "3001:3001"