version: '2'
services:

  frontend:
    build: ./courseify_client
    container_name: courseify_client
    command: npm run start
    ports:
      - '3001:80'
    volumes:
     - ./frontend:/courseify_client
    environment:
      NODE_ENV: development

  backend:
    build: ./courseify_api
    container_name: courseify_api
    command: rails s -b 0.0.0.0 -p 3000
    ports:
      - '3000:80'
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - bundle:/usr/local/bundle
      - db_data:/var/lib/postgresql/data
    environment:
      RAILS_ENV: development

  db:
    image: postgres:9.6
    container_name: couresify_db
    ports:
      - '5432'

volumes:
  db_data:
  bundle: